const hospitals = [
    {
      id: 1,
      name: "Lagos University Teaching Hospital",
      location: "Idi-Araba, Lagos State",
      address: "Idi-Araba, Lagos State",
      phone: "+234 810 000 0001",
      email: "info@luth.ng",
    },
    {
      id: 2,
      name: "University College Hospital",
      location: "Ibadan, Oyo State",
      address: "Queen Elizabeth Road, Ibadan, Oyo State",
      phone: "+234 810 000 0002",
      email: "contact@uch.ng",
    },
    {
      id: 3,
      name: "National Hospital Abuja",
      location: "Central Business District, Abuja FCT",
      address: "Central Business District, Abuja FCT",
      phone: "+234 810 000 0003",
      email: "admin@nationalhospital.ng",
    },
    {
      id: 4,
      name: "Ahmadu Bello University Teaching Hospital",
      location: "Zaria, Kaduna State",
      address: "Zaria, Kaduna State",
      phone: "+234 810 000 0004",
      email: "abuth@abuth.ng",
    },
    {
      id: 5,
      name: "Obafemi Awolowo University Teaching Hospital",
      location: "Ile-Ife, Osun State",
      address: "Ile-Ife, Osun State",
      phone: "+234 810 000 0005",
      email: "info@oauth.ng",
    },
    {
      id: 6,
      name: "University of Nigeria Teaching Hospital",
      location: "Ituku-Ozalla, Enugu State",
      address: "Ituku-Ozalla, Enugu State",
      phone: "+234 810 000 0006",
      email: "contact@unth.ng",
    },
    {
      id: 7,
      name: "Nnamdi Azikiwe University Teaching Hospital",
      location: "Nnewi, Anambra State",
      address: "Nnewi, Anambra State",
      phone: "+234 810 000 0007",
      email: "admin@nauth.ng",
    },
    {
      id: 8,
      name: "Babcock University Teaching Hospital",
      location: "Ilishan-Remo, Ogun State",
      address: "Ilishan-Remo, Ogun State",
      phone: "+234 810 000 0008",
      email: "info@buth.ng",
    },
    {
      id: 9,
      name: "Federal Medical Centre, Abeokuta",
      location: "Idi-Aba, Abeokuta, Ogun State",
      address: "Idi-Aba, Abeokuta, Ogun State",
      phone: "+234 810 000 0009",
      email: "contact@fmcabeokuta.ng",
    },
    {
      id: 10,
      name: "University of Benin Teaching Hospital",
      location: "Ugbowo, Benin City, Edo State",
      address: "Ugbowo, Benin City, Edo State",
      phone: "+234 810 000 0010",
      email: "ubth@ubth.ng",
    },
    {
      id: 11,
      name: "Federal Medical Centre, Asaba",
      location: "Okpanam Road, Asaba, Delta State",
      address: "Okpanam Road, Asaba, Delta State",
      phone: "+234 810 000 0011",
      email: "info@fmcasaba.ng",
    },
    {
      id: 12,
      name: "Federal Teaching Hospital, Gombe",
      location: "Ashaka Road, Gombe, Gombe State",
      address: "Ashaka Road, Gombe, Gombe State",
      phone: "+234 810 000 0012",
      email: "contact@fthgombe.ng",
    },
    {
      id: 13,
      name: "University of Ilorin Teaching Hospital",
      location: "Oke-Ose, Ilorin, Kwara State",
      address: "Oke-Ose, Ilorin, Kwara State",
      phone: "+234 810 000 0013",
      email: "info@uith.ng",
    },
    {
      id: 14,
      name: "Federal Medical Centre, Keffi",
      location: "Along Nasarawa Road, Keffi, Nasarawa State",
      address: "Along Nasarawa Road, Keffi, Nasarawa State",
      phone: "+234 810 000 0014",
      email: "admin@fmckeffi.ng",
    },
    {
      id: 15,
      name: "Federal Medical Centre, Yenagoa",
      location: "Swali, Yenagoa, Bayelsa State",
      address: "Swali, Yenagoa, Bayelsa State",
      phone: "+234 810 000 0015",
      email: "info@fmcyenagoa.ng",
    },
    {
      id: 16,
      name: "Lagos State University Teaching Hospital",
      location: "Ikeja, Lagos State",
      address: "Ikeja, Lagos State",
      phone: "+234 810 000 0016",
      email: "contact@lasuth.ng",
    },
    {
      id: 17,
      name: "Ekiti State University Teaching Hospital",
      location: "Ado-Ekiti, Ekiti State",
      address: "Ado-Ekiti, Ekiti State",
      phone: "+234 810 000 0017",
      email: "info@eksuth.ng",
    },
    {
      id: 18,
      name: "Delta State University Teaching Hospital",
      location: "Oghara, Delta State",
      address: "Oghara, Delta State",
      phone: "+234 810 000 0018",
      email: "admin@delsuth.ng",
    },
    {
      id: 19,
      name: "Federal Medical Centre, Owo",
      location: "Along Ifon Road, Owo, Ondo State",
      address: "Along Ifon Road, Owo, Ondo State",
      phone: "+234 810 000 0019",
      email: "info@fmcowo.ng",
    },
    {
      id: 20,
      name: "University of Port Harcourt Teaching Hospital",
      location: "Alakahia, Port Harcourt, Rivers State",
      address: "Alakahia, Port Harcourt, Rivers State",
      phone: "+234 810 000 0020",
      email: "contact@upth.ng",
    },
    {
      id: 21,
      name: "Federal Medical Centre, Umuahia",
      location: "Amachara, Umuahia, Abia State",
      address: "Amachara, Umuahia, Abia State",
      phone: "+234 810 000 0021",
      email: "info@fmcumuahia.ng",
    },
    {
      id: 22,
      name: "University of Uyo Teaching Hospital",
      location: "Abak Road, Uyo, Akwa Ibom State",
      address: "Abak Road, Uyo, Akwa Ibom State",
      phone: "+234 810 000 0022",
      email: "admin@uuth.ng",
    },
    {
      id: 23,
      name: "Federal Medical Centre, Makurdi",
      location: "Apir Road, Makurdi, Benue State",
      address: "Apir Road, Makurdi, Benue State",
      phone: "+234 810 000 0023",
      email: "info@fmcmakurdi.ng",
    },
    {
      id: 24,
      name: "University of Jos Teaching Hospital",
      location: "Lamingo, Jos, Plateau State",
      address: "Lamingo, Jos, Plateau State",
      phone: "+234 810 000 0024",
      email: "contact@ujth.ng",
    },
    {
      id: 25,
      name: "Federal Medical Centre, Owerri",
      location: "Orlu Road, Owerri, Imo State",
      address: "Orlu Road, Owerri, Imo State",
      phone: "+234 810 000 0025",
      email: "info@fmcowerri.ng",
    },
    {
      id: 26,
      name: "Federal Medical Centre, Bida",
      location: "Along Mokwa Road, Bida, Niger State",
      address: "Along Mokwa Road, Bida, Niger State",
      phone: "+234 810 000 0026",
      email: "contact@fmcbida.ng",
    },
    {
      id: 27,
      name: "Olabisi Onabanjo University Teaching Hospital",
      location: "Sagamu, Ogun State",
      address: "Sagamu, Ogun State",
      phone: "+234 810 000 0027",
      email: "info@oouth.ng",
    },
    {
      id: 28,
      name: "Federal Medical Centre, Birnin Kebbi",
      location: "Kalgo Road, Birnin Kebbi, Kebbi State",
      address: "Kalgo Road, Birnin Kebbi, Kebbi State",
      phone: "+234 810 000 0028",
      email: "contact@fmcbernin.ng",
    },
    {
      id: 29,
      name: "Irrua Specialist Teaching Hospital",
      location: "Irrua, Edo State",
      address: "Irrua, Edo State",
      phone: "+234 810 000 0029",
      email: "info@isth.ng",
    },
    {
      id: 30,
      name: "Federal Medical Centre, Ido-Ekiti",
      location: "Ado-Ikare Road, Ido-Ekiti, Ekiti State",
      address: "Ado-Ikare Road, Ido-Ekiti, Ekiti State",
      phone: "+234 810 000 0030",
      email: "contact@fmcido.ng",
    },
    {
      id: 31,
      name: "Federal Medical Centre, Katsina",
      location: "Mani Road, Katsina, Katsina State",
      address: "Mani Road, Katsina, Katsina State",
      phone: "+234 810 000 0031",
      email: "info@fmckatsina.ng",
    },
    {
      id: 32,
      name: "Federal Medical Centre, Lokoja",
      location: "Okene Road, Lokoja, Kogi State",
      address: "Okene Road, Lokoja, Kogi State",
      phone: "+234 810 000 0032",
      email: "contact@fmclokoja.ng",
    },
    {
      id: 33,
      name: "University of Maiduguri Teaching Hospital",
      location: "Bama Road, Maiduguri, Borno State",
      address: "Bama Road, Maiduguri, Borno State",
      phone: "+234 810 000 0033",
      email: "info@umth.ng",
    },
    {
      id: 34,
      name: "Federal Medical Centre, Gusau",
      location: "Sokoto Road, Gusau, Zamfara State",
      address: "Sokoto Road, Gusau, Zamfara State",
      phone: "+234 810 000 0034",
      email: "contact@fmcgusau.ng",
    },
    {
      id: 35,
      name: "Federal Medical Centre, Azare",
      location: "Misau Road, Azare, Bauchi State",
      address: "Misau Road, Azare, Bauchi State",
      phone: "+234 810 000 0035",
      email: "info@fmcazare.ng",
    },
    {
      id: 36,
      name: "Federal Medical Centre, Nguru",
      location: "Along Gashua Road, Nguru, Yobe State",
      address: "Along Gashua Road, Nguru, Yobe State",
      phone: "+234 810 000 0036",
      email: "contact@fmcnguru.ng",
    },
    {
      id: 37,
      name: "Federal Medical Centre, Jalingo",
      location: "Wukari Road, Jalingo, Taraba State",
      address: "Wukari Road, Jalingo, Taraba State",
      phone: "+234 810 000 0037",
      email: "info@fmcjalingo.ng",
    },
    {
      id: 38,
      name: "Federal Medical Centre, Birnin Kudu",
      location: "Kano Road, Birnin Kudu, Jigawa State",
      address: "Kano Road, Birnin Kudu, Jigawa State",
      phone: "+234 810 000 0038",
      email: "contact@fmcbirnin.ng",
    },
    {
      id: 39,
      name: "Federal Medical Centre, Ikom",
      location: "Calabar Road, Ikom, Cross River State",
      address: "Calabar Road, Ikom, Cross River State",
      phone: "+234 810 000 0039",
      email: "info@fmcikom.ng",
    },
    {
      id: 40,
      name: "University of Abuja Teaching Hospital",
      location: "Gwagwalada, Abuja FCT",
      address: "Gwagwalada, Abuja FCT",
      phone: "+234 810 000 0040",
      email: "contact@uath.ng",
    },
  ];
  
  export default hospitals